if(NOT COMPILER_PATH)
  if (EXISTS /opt/sw_home/local/bin/clang++)
    set(COMPILER_PATH /opt/sw_home/local/bin)
  elseif (EXISTS /usr/local/corex/bin/clang++)
    set(COMPILER_PATH /usr/local/corex/bin)
  else()
    message(STATUS "COMPILER_PATH is not set and we couldn't find clang compiler neither, will use system C/C++ compiler")
  endif()
endif()
if (COMPILER_PATH)
  set(CMAKE_CXX_COMPILER ${COMPILER_PATH}/clang++)
  set(CMAKE_C_COMPILER ${COMPILER_PATH}/clang)
endif()

message(STATUS "Use ${CMAKE_CXX_COMPILER} and ${CMAKE_C_COMPILER} as C++ and C compiler")